defaults:
  - IHM.yaml

name: FingerGaiting

sim:
  gravity: [0.0, 0.0, -9.81]

# finger gaiting specific configs
fingerGaiting:
  object_tilt_lim: 0.8

env:
  episodeLength: 512
  use_saved_grasps: False
  saved_grasps: 
    cylinder:
    cube:
    13x6_cuboid: 
    10x8x8x4_L:
  saved_tree: 

  # observation and state
  feedbackObs: ["hand_joint_pos",  "hand_joint_target", "ftip_contact_bool"]
  feedbackState: ["hand_joint_pos",  "hand_joint_target", "ftip_contact_force", "object_pos", "object_orientation", "object_lin_vel", "object_ang_vel", "hand_joint_torque", "ftip_contact_pos"]

  reset:
    obj_xyz_lower_lim: [-5.0, -5.0, 0.0]
    obj_xyz_upper_lim: [5.0, 5.0, 2.0]

  # reward terms
  reward:
    angVelClipMax: 0.5
    angVelClipMin: -0.5
    rotationRewardScale: 1.0
    objectLinVelPenaltyScale: -0.3
    poseDiffPenaltyScale: -0.0 # leave as is, scripts will handle changing when necessary
    torquePenaltyScale: -0.0
    workPenaltyScale: 0.0
    ftip_obj_disp_pen: 0.0
    out_of_bounds_pen: 0.0


