defaults:
  - IHM.yaml

name: HANDEM

env:
  object_dataset: '3DPrintedShapes'
  objectOverride:
  episodeLength: 300
  use_saved_grasps: False

  # observation and state
  feedbackObs: ["hand_joint_pos",  "hand_joint_target", "ftip_contact_bool"]
  feedbackState: ["hand_joint_pos",  "hand_joint_target", "ftip_contact_force", "object_pos", "object_orientation", "object_lin_vel", "object_ang_vel", "hand_joint_torque", "ftip_contact_pos"]

  reset:
    confidence_threshold: 0.98
    obj_xyz_lower_lim: [0.105, 0.45, 0.0]
    obj_xyz_upper_lim: [0.145, 0.55, 0.3]

  # reward terms
  reward:
    # correct discriminator prediction
    disc_pred_reward: 500.0
    # log likelihood reward
    disc_loss_reward: 1.0


