defaults:
  - IHM.yaml

name: HANDEM_Reconstruct

env:
  object_dataset: 'Tandem2D'
  objectOverride: 
  episodeLength: 100
  use_saved_grasps: False
  rand_object_reset: True

  fix_object: True
  edge_loss_lambda: 0.01
  # observation and state
  feedbackObs: ["hand_joint_pos",  "hand_joint_target", "ftip_contact_bool"]
  feedbackState: ["hand_joint_pos",  "hand_joint_target", "ftip_contact_force", "object_pos", "object_orientation", "object_lin_vel", "object_ang_vel", "hand_joint_torque"]

  propHistoryRange: 100 # how far to look back
  propHistoryFreq: 10 # how often to include prev obs in hist buf
  obsHistoryRange: 100
  obsHistoryFreq: 10

  reset:
    loss_threshold: 1e-4
    obj_xyz_lower_lim: [0.0, 0.35, 0.0]
    obj_xyz_upper_lim: [0.3, 0.65, 0.5]

  # reward terms
  reward:
    reg_loss_reward: 1.0
    reg_loss_temp: 0.01
    # heuristic terms
    ftip_obj_dist_rew: 0.05 # encourage contact
    object_disp_rew: 0.0 # encourage object to stay in place
    contact_loc_pen: 0.0 # penalize contact with back of fingertips
    hand_pose_pen: 0.01 # penalize hand joint disp from "close-hand"

  randomize: False
  randomization_params:
    observation:
      sigma: 0.01
      tactile: 0.5 # uniform noise in range [0.0, tactile]


